app.name=JKS Viewer
app.version=${appVersion}
app.vendor=Silent Crane
app.repository=https://github.com/yin2hao-windowsTools/jks-viewer
app.developerHomepage=https://github.com/yin2hao-windowsTools
app.license=Unspecified
app.releaseApi=https://api.github.com/repos/yin2hao-windowsTools/jks-viewer/releases/latest
